settings:
  title: 'Avonis Status Page'
  url: 'https://status.avonis.app/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Operational Outage'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: avonis-app # unique identifier
    name: Website
    description: 'Frontend Application built with bulma' # default=empty
    url: 'https://avonis.app/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cdn-avonis-app
    name: Avonis CDN
    description: 'Content Delivery Network for Avonis'
    url: 'https://cdn.avonis.app/'
    method: GET
    expectStatus: 403
